### ISSUE TITLE
Choosing what css to output

### ISSUE THREAD

**Issue by dawidvdh** [jkphl/grunt-iconizr#18]
Hi Great Plugin! Just two questions:

I have created a custom template which works beautifully. But it still outputs 4 stylesheets, my custom one and then 3 others, Is there anyway for it to only output my custom template and non of the others?

Then Also, if i set it to output to 'liveload/img' it creates an additional folder called 'icon', is there any way to not create the additional folder?

Here is my current configuration:
```javascript
iconizr: {
            options: {
                // Task-specific options go here.
                dims    : true,
                common: 'img',
                recursive: true,
                render    : {
                    css     : false,
                    scss    : {
                        template    : 'config/sprite.hbs',
                        dest        : '../../compass/source/_icons.scss'
                    }

                },
                variables   : {
                    png: function() {
                        return function(sprite, render) {
                            return render(sprite).split('.svg').join('.png');
                        }
                    }
                }
            },
            bsWatch: {
                src         : ['iconizr/source'],
                dest        : 'liveload',
            }
        }
```

i am using bsWatch task currently.

Any Help would be Greatly Appreciated.

**Comment by jkphl** [comment]
Hi @dawidvdh,

first of all sorry for not getting back to you earlier — and Happy New Year! :)

I'm not sure if I fully understand your question(s), but I'll try:

1. It's iconizr's **ultimate sense** to always output several stylesheet resources in parallel. Please read the [node-iconizr introduction](https://github.com/jkphl/node-iconizr#iconizr) to get an idea of why and what they're good for. Using the JavaScript loader resource, your client (browser) will choose which one fits him best. You wouldn't want to get rid of them.

2. Is it possible that the directory created is named `icons` (instead of `icon`)? I guess this must be the `spritedir` option. Please set it to `"."` to avoid that directory.

I'll close this issue for now, but please feel free to re-open it if you've still got problems.

Cheers,
Joschi
