### ISSUE TITLE
Is it possible to bypass PNG sprite creation in dev builds?

### ISSUE THREAD

**Issue by ddimaria** [jkphl/grunt-iconizr#24]
As a project grows, the PNG creation mechanism can take a while to process.  As a method of streamlining the dev workflow, it is possible to bypass the PNG sprite creation, but still get iconizr to generate stylesheet resources?

**Comment by jkphl** [comment]
Not at present. I might consider it for the upcoming release though (due within the next 2 weeks). Stay tuned! ;)
Cheers, Joschi

**Comment by jkphl** [comment]
I was just about implementing a `skip` option into the new version of _node-iconizr_ when I realized that it's not really possible to skip the creation of the PNG fallbacks. At least one of the four stylesheets (the PNG dataURI one) couldn't be created in this case. Also, the new version will feature a cache busting option, which needs to create a hash from each of the CSS files.

Instead of disabling the creation of PNG fallbacks altogether, I recommend disabling only the PNG optimization by setting `level` to zero, which should save you lots of time as well. I hope this works for you! Thanks for your understanding.

Cheers,
Joschi
