### ISSUE TITLE
Custom template not working

### ISSUE THREAD

**Issue by benfrain** [jkphl/grunt-iconizr#30]
First is a tiny thing that could be fixed:

If I overwrite the existing template in node_modules/grunt-iconizr/node_modules/iconizr/tmpl/sprite.scss and don't delete the existing sprite sheets in the destination folder, the new template changes are not picked up. This made me think it wasn't working altogether. Once I deleted the folder contents it started to get picked up again.

**Comment by benfrain** [comment]
Sorry, finally figured this out.

**Comment by jkphl** [comment]
@benfrain No problem, Ben.

Currently grunt-/node-iconizr is still based on the "old" svg-sprite base, as I'm so totally overloaded these days (moving my office next Friday ...) and don't manage to finalise the next generation somehow. However, there's already a new version of (grunt-)iconizr here on GitHub — if you're interested, please check the "dev" branches of [node-iconizr](https://github.com/jkphl/node-iconizr/tree/dev) and [grunt-iconizr](https://github.com/jkphl/grunt-iconizr/tree/dev). Unfortunately there's no proper documentation yet (that's why I didn't release it), but we already do use it in production. For now, [this](https://github.com/jkphl/node-iconizr/blob/dev/README.md) would be your best bet as a manual.
